//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunicationManagement
{
    using DatabaseManagement;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using VacationManagement;

    public class EmailService
    {
        public const String CONFIRMATION_EMAIL_SUBMISSION = "SUBMISSION";
        public const String CONFIRMATION_EMAIL_AGREED = "AGREED";
        public const String CONFIRMATION_EMAIL_PERMITTED = "PERMITTED";
        public const String CONFIRMATION_EMAIL_REJECTED = "REJECTED";


        /// <summary>
        /// informs the respective persons about the new status
        /// </summary>
        /// <param name="VacationRequest">VacationRequest of the Requester</param>
        /// <param name="message">Content of email</param>
        /// <returns></returns>
        public void sendMessage(VacationRequest vacationRequest, String message)
        {
                    
            DBQuery dbq = new DBQuery();

            if (message.Equals("SUBMISSION")) 
            {
                Employee deputy = dbq.SelectDeputy(vacationRequest.getEmployeeID());
                Employee divisionManager = dbq.SelectDivisionManager(vacationRequest.getEmployeeID());
                
                // TODO: implement Email sending procedure 
  
            }
            else if (message.Equals("AGREED"))
            {
                Employee divisionManager = dbq.SelectDivisionManager(vacationRequest.getEmployeeID());
                Employee requester = dbq.SelectRequester(vacationRequest.getVacationRequestID());

                // TODO: implement Email sending procedure 
            }
            else if (message.Equals("PERMITTED"))
            {
                
            }
            else if (message.Equals("REJECTED"))
            {
                Employee requester = dbq.SelectRequester(vacationRequest.getVacationRequestID());

                // TODO: implement Email sending procedure 

            }
        }

    }
}

