//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VacationManagement;

namespace GUIManagement
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using DatabaseManagement;

    public class VacationReplacementRequestViewItem
    {
        private ulong _vacationRequestID;
        private String _requesterID;
        private DateTime _vacationStartDate;
        private DateTime _vacationEndDate;
        private int _netVacationDays;
        private String _requesterFullName;
        private VacationRequestProcessingState _vacationRequestProcessingState;



        public ulong VacationRequestID
        {
            get { return _vacationRequestID; }
        }

        public String VacationRequestIDViewString
        {
            get { return _vacationRequestID.ToString(); }
        }


        public String RequesterID
        {
            get { return _requesterID; }
        }

        public String VacationStartDateViewString
        {
            get { return _vacationStartDate.ToShortDateString(); }
        }

        public String VacationEndDateViewString
        {
            get { return _vacationEndDate.ToShortDateString(); }
        }

        public String NetVacationDaysViewString
        {
            get { return Convert.ToString(_netVacationDays); }
        }



        public String RequesterFullName
        {
            get { return _requesterFullName; }
        }


        public String VacationRequestProcessingStateViewString
        {
            get
            {
                return VacationRequestProcessingStateConverter.ConvertStateToString(_vacationRequestProcessingState);
            }
        }


        public VacationReplacementRequestViewItem()
        {

        }

        public VacationReplacementRequestViewItem(VacationRequest vacationRequest, String requesterFullName)
        {
            this._vacationRequestID = vacationRequest.getVacationRequestID();
            this._requesterID = vacationRequest.getEmployeeID();
            this._vacationStartDate = vacationRequest.getVacationStartDate();
            this._vacationEndDate = vacationRequest.getVacationEndDate();
            this._netVacationDays = vacationRequest.getNetVacationDays();
            this._requesterFullName = requesterFullName;
            this._vacationRequestProcessingState = vacationRequest.getVacationRequestProcessingState();

        }
    }
}