//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEule
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.SickNotes = new HashSet<SickNote>();
            this.VacationEntitlements = new HashSet<VacationEntitlement>();
            this.VacationRequests = new HashSet<VacationRequest>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string StaffID { get; set; }
        public Nullable<int> ShiftGroupID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual Division Division { get; set; }
        public virtual ShiftGroup ShiftGroup { get; set; }
        public virtual ICollection<SickNote> SickNotes { get; set; }
        public virtual ICollection<VacationEntitlement> VacationEntitlements { get; set; }
        public virtual ICollection<VacationRequest> VacationRequests { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
