//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.VacationLockPeriods = new HashSet<VacationLockPeriod>();
        }
    
        public int DivisionID { get; set; }
        public string DivisionTitle { get; set; }
        public string DivisionManagerID { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<VacationLockPeriod> VacationLockPeriods { get; set; }
    }
}
