//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EuleApp_DatabaseEntityModel : DbContext
    {
        public EuleApp_DatabaseEntityModel()
            : base("name=EuleApp_DatabaseEntityModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<ShiftGroup> ShiftGroups { get; set; }
        public virtual DbSet<SickNote> SickNotes { get; set; }
        public virtual DbSet<VacationEntitlement> VacationEntitlements { get; set; }
        public virtual DbSet<VacationLockPeriod> VacationLockPeriods { get; set; }
        public virtual DbSet<VacationReplacementRequest> VacationReplacementRequests { get; set; }
        public virtual DbSet<VacationRequest> VacationRequests { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
    }
}
