//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEule
{
    using System;
    using System.Collections.Generic;
    
    public partial class SickNote
    {
        public int SickNoteID { get; set; }
        public System.DateTime SickLeaveStartDate { get; set; }
        public System.DateTime SickLeaveEndDate { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
