//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEule
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationEntitlement
    {
        public int VacationEntitlementID { get; set; }
        public int VacationDaysTotal { get; set; }
        public int VacationDaysPreviousYear { get; set; }
        public int VacationDayRemaining { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
