//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEule
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationReplacementRequest
    {
        public int ReplacementRequestID { get; set; }
        public string ReplacementProcessingState { get; set; }
        public long VacationRequestID { get; set; }
    
        public virtual VacationRequest VacationRequest { get; set; }
    }
}
