//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEule
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationLockPeriod
    {
        public int LockPeriodID { get; set; }
        public System.DateTime LockPeriodStartDate { get; set; }
        public System.DateTime LockPeriodEndDate { get; set; }
        public int DivisionID { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
