//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace VacationManagement
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Employee
    {
        private String _employeeID;
       
        private String _loginName;
        private String _loginPassword;
        private String _lastName;
        private String _firstName;
        private String _emailAddress;
        private int _staffID;
        private String _role;
        private int _shiftGroupID;
        private int _divisionID;


        public String getEmployeeID()
        {
            return _employeeID;
        }
        public String EmployeeID
        {
            get { return _employeeID; }
          
        }

        [DisplayName("Benutzername")]
        public String UserName
        {
            get { return _loginName; }
        }

         [DisplayName("Nachname")]
        public String LastName
        {
            get {return _lastName;}
        }

        [DisplayName("Vorname")]
        public String FirstName
        {
            get { return _firstName; }
        }

        [DisplayName("E-Mail")]
        public String EmailAddress
        {
           get {return _emailAddress;}
        }

        [DisplayName("Rolle")]
        public String Role
        {
            get { return _role; }
            set { _role = value; }
        }


        
      

        public String getFullName() 
        {
            return _firstName + " " + _lastName;
        }

        public Employee(String EmployeeID, String LoginName, String LoginPassword, String FirstName, String LastName, String EmailAddress, int StaffID, String Role, int ShiftGroupID, int DivisionID)
        {
            _employeeID = EmployeeID;
            _loginName = LoginName;
            _loginPassword = LoginPassword;
            _lastName = LastName;
            _firstName = FirstName;
            _emailAddress = EmailAddress;
            _staffID = StaffID;
            _role = Role;
            _shiftGroupID = ShiftGroupID;
            _divisionID = DivisionID;
        }
        public Employee(String EmployeeID, String LoginName, String LoginPassword, String FirstName, String LastName, String EmailAddress, int ShiftGroupID, int DivisionID)
        { //without Role and StaffID!
            _employeeID = EmployeeID;
            _loginName = LoginName;
            _loginPassword = LoginPassword;
            _lastName = LastName;
            _firstName = FirstName;
            _emailAddress = EmailAddress;
            _shiftGroupID = ShiftGroupID;
            _divisionID = DivisionID;
        }
    }
}

