//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VacationManagement
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// the possible ProcessingState of a VacationRequest
    /// </summary>
    public enum VacationRequestProcessingState : int
    {
        submitted,
        agreed,
        rejectedByDeputy,
        rejectedByDivisionManager, 
        permitted,
        approved,
        canceled,
        taken,
    }
}