//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Specialized;

namespace VacationManagement
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class VacationRequestIDGenerator
    {
        /// <summary>
        /// generates a unique vactionRequestID
        /// </summary>
        /// <param name="EmployeeID"> the EmployeeID of the creator</param>
        /// <returns>vactionRequestID</returns>
        public ulong GenerateID(String EmployeeID) 
        {
            DateTime moment = DateTime.Now;      
            long timestamp = moment.Ticks - new DateTime(1970, 1, 1).Ticks;
            long iDHash = EmployeeID.GetHashCode();
            ulong vactionRequestID = (ulong)((timestamp & 0x0000FFFFFFFFFFFF) | (iDHash << 48));
            return vactionRequestID;        
        }

        public static VacationRequestIDGenerator GetIDGeneratorInstance
        {
            get 
            {
                if (_idGeneratorInstance == null)
                {
                    _idGeneratorInstance = new VacationRequestIDGenerator();
                }
                return _idGeneratorInstance;
            }
        }

        private VacationRequestIDGenerator()
        {
        }

        private static VacationRequestIDGenerator _idGeneratorInstance;
    }
}

